name: 'Check pull request title conventions'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: tr4n/action-pr-title@master
        with:
          regex: '^[ ]*\[(TASK|BUG|FEATURE|TEST|SUPPORT)*-[0-9.]*\][ ]*:.*' # Example: [TASK-123]: Configure database
